language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
