language: java

os: osx
osx_image: xcode7.3

install:
  - [[ ! -f ~/sbt ]] && \
    curl -s https://raw.githubusercontent.com/paulp/sbt-extras/e428bbdb514e1ffe245010b3c4f69e9dfa4bbdb3/sbt > ~/sbt && \
    chmod 0755 ~/sbt
  - java -version

cache:
  directories:
    - ~/sbt
    - ~/.ivy2
    - ~/.sbt

script:
  - ~/sbt test test-ui:test

# Disable notifications (rely on Appveyor for build emails)
notifications:
  email: false
