language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

env:
  global:
    # Codacy project token
    secure: smnTaYYUBEU1nGqKOVnnAzyRQp8VQR/V5ZQfW5x1Vh2ZhabZOhBZBaEZI9vDOjBDEcjpvbPkHxTNoZQ+DvIpVokn/ClULMKo1pzAc+71RluAGw156s4VbGKTlgn4wpgzIja0fw1m+Zwf854lhpia7/T/QwGjWTkaI+EWfcBBVenEOu+pk2MIjP9hARqhOeqNq5N/AgPLxnpk5jkyrjqASzEzN+m71U93NFuWa3h5LJcdLuT406M3XG5D77Mjl6lXuORvj7IgzKXgKBQveVERlYf5MmZSRrtl98SeLmm413zJNlm/LEkWyq28j6s5nwSEypiDee/gugJ4Olm1eD61GCr0am+wNscl4o0SDPCZH8AeaxdI2yW96xFh91rQw9qfCx+tPCKE8QXZu8kJtrQ39qHhhEnqdZGGZIwdM+KrbrNIGcJ8NFjvO1lNsseVV8pJgAJ3N55UGPOFZ19qAbIz08QbELJQbJVcGWcnifHDbi1AK41K70kHGBBPzxWMqn/4GaVZP3hr2a7pKkyj7Y1gCXSRggP22CVcUnQ8DqmdBBENM27Bb+61WfUYjCwxrb7ui+j7dyaPYYxWkq2jf9Lcz9OnQ0147GMUuW/lEeYtE5Z2wtrNZQgvBACNb4qEDSvqThqQ0yJ/suUhbOfWxIpFZx7yWiDDiR7E8FyP4eLiWpM=

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test test-ui:test coverageReport codacyCoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Disable notifications (rely on Appveyor for build emails)
notifications:
  email: false
