version: '{build}'

os: Windows Server 2012

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dl.bintray.com/sbt/native-packages/sbt/0.13.11/sbt-0.13.11.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - cmd: set PYTHON=C:\Python35
  - cmd: set PATH=C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PYTHON%\Scripts;%PATH%
  - cmd: set SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: set JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: pip install --disable-pip-version-check codecov
  - cmd: java -version

build_script:
  - sbt windows:packageBin

test_script:
  - sbt coverage test test-ui:test coverageReport

after_test:
  - codecov

artifacts:
  - path: 'target\scala-*\*.jar'
    name: Java Package
  - path: 'target\windows\*.msi'
    name: Windows Installer

deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: ''
  auth_token:
    secure: XSSEVEdWgj60ZMOTimzmd92UJc4aP5B46CuNM+y2llK6onAqOoM0Y5RcIrCD3dZF
  # Note: regexp is needed here, vs. ant-style path in artifacts section
  artifact: /target\\windows\\.*\.msi/
  draft: false
  prerelease: true
  on:
    appveyor_repo_tag: true

cache:
  - C:\sbt\
  - '%USERPROFILE%\.ivy2\'
  - '%USERPROFILE%\.sbt\'
